[package]
name = "superscraper-mee6"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2", features = ["json"] }
serde = { version = "1", features = ["derive"] } 
serde_json = "1"
