name: Check build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build linux
        run: go build .
        
      - name: Build windows
        run: go build .
        env: 
          GOOS: windows
          GOARCH: 386
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executables
          path: |
            mee6-scraper
            mee6-scraper.exe
