name: Check build
on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build go
        run: go build .