name: Get minecraft discord
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get date
        id: date
        run: echo "NOW=$(date +'%Y-%m-%dT%Hh%Mm')" >> $GITHUB_ENV

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: snapshot-${{ env.NOW }}
          message: level archive for ${{ env.NOW }}

      - name: Run go
        run: go run . 302094807046684672

      - name: Upload json
        uses: actions/upload-artifact@v3
        with:
          name: data
          path: 302094807046684672-levels.json
