name: Get minecraft discord
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run go
        run: go run 302094807046684672

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: scrape.json
          path: ./scrape.json

