name: Get minecraft discord
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get date
        id: date
        run: echo "NOW::date=$(date +'%Y-%m-%dT%H:%M')" >> $GITHUB_ENV

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: snapshot-$NOW
          message: level archive for $NOW

      - name: Run go
        run: go run . 302094807046684672

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Snapshot $NOW
          tag_name: snapshot-$NOW
          files: |
            302094807046684672-levels.json
            302094807046684672-levels.sql
