name: Get minecraft discord
on:
  schedule:
    - "0 0 * * *"
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Scrape
        run: python ./scrape.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: data.sql
          path: ./import.sql

