name: Get minecraft discord
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run go
        run: go run . 302094807046684672

      - name: Get date
        id: date
        run: echo "::set-output date=$(date +'%Y-%m-%dT%H:%M')"

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: snapshot-${{ steps.date.outputs.date }}
          message: level archive for ${{ steps.date.outputs.date }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Snapshot ${{ steps.date.outputs.date }}
          files: |
            302094807046684672-levels.json
            302094807046684672-levels.sql
